import time
print("discord: purify.rip_")
print("discord: purify.rip_")
print("discord: purify.rip_")
print("discord: purify.rip_")
print("discord: purify.rip_")
print("discord: purify.rip_")
print("discord: purify.rip_")
print("discord: purify.rip_")
time.sleep(1000)
