import time
print("CONTACT ON DISCORD FOR SRC: purify.rip_")
print("CONTACT ON DISCORD FOR SRC: purify.rip_")
print("CONTACT ON DISCORD FOR SRC: purify.rip_")
print("CONTACT ON DISCORD FOR SRC: purify.rip_")
print("CONTACT ON DISCORD FOR SRC: purify.rip_")
print("CONTACT ON DISCORD FOR SRC: purify.rip_")
print("CONTACT ON DISCORD FOR SRC: purify.rip_")
print("CONTACT ON DISCORD FOR SRC: purify.rip_")
print("CONTACT ON DISCORD FOR SRC: purify.rip_")
print("CONTACT ON DISCORD FOR SRC: purify.rip_")
print("CONTACT ON DISCORD FOR SRC: purify.rip_")
print("CONTACT ON DISCORD FOR SRC: purify.rip_")
print("CONTACT ON DISCORD FOR SRC: purify.rip_")
print("CONTACT ON DISCORD FOR SRC: purify.rip_")
print("CONTACT ON DISCORD FOR SRC: purify.rip_")
print("CONTACT ON DISCORD FOR SRC: purify.rip_")
print("CONTACT ON DISCORD FOR SRC: purify.rip_")
print("CONTACT ON DISCORD FOR SRC: purify.rip_")
print("CONTACT ON DISCORD FOR SRC: purify.rip_")
print("CONTACT ON DISCORD FOR SRC: purify.rip_")
print("CONTACT ON DISCORD FOR SRC: purify.rip_")
print("CONTACT ON DISCORD FOR SRC: purify.rip_")
print("CONTACT ON DISCORD FOR SRC: purify.rip_")
print("CONTACT ON DISCORD FOR SRC: purify.rip_")
print("CONTACT ON DISCORD FOR SRC: purify.rip_")
print("CONTACT ON DISCORD FOR SRC: purify.rip_")
print("CONTACT ON DISCORD FOR SRC: purify.rip_")
print("CONTACT ON DISCORD FOR SRC: purify.rip_")
print("CONTACT ON DISCORD FOR SRC: purify.rip_")
print("CONTACT ON DISCORD FOR SRC: purify.rip_")
print("CONTACT ON DISCORD FOR SRC: purify.rip_")
print("CONTACT ON DISCORD FOR SRC: purify.rip_")
print("CONTACT ON DISCORD FOR SRC: purify.rip_")
print("CONTACT ON DISCORD FOR SRC: purify.rip_")
print("CONTACT ON DISCORD FOR SRC: purify.rip_")
time.sleep(1)
print("https://tiktool.pro reverse engineer API")
print("https://tiktool.pro reverse engineer API")
print("https://tiktool.pro reverse engineer API")
print("https://tiktool.pro reverse engineer API")
print("https://tiktool.pro reverse engineer API")
print("https://tiktool.pro reverse engineer API")
print("https://tiktool.pro reverse engineer API")
print("https://tiktool.pro reverse engineer API")
print("https://tiktool.pro reverse engineer API")
print("https://tiktool.pro reverse engineer API")
print("https://tiktool.pro reverse engineer API")
print("https://tiktool.pro reverse engineer API")
print("https://tiktool.pro reverse engineer API")
print("https://tiktool.pro reverse engineer API")
time.sleep(1)
print("CONTACT ON DISCORD FOR SRC: purify.rip_")
input("Press Enter To Exit: ")
